version: 1.0.{build}

image: Visual Studio 2017

environment:
  nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - cd frontend
  - yarn install
  - cd ..

build_script:
  - ps: .\backend\build.ps1 -Target Publish
  - cd frontend
  - yarn run ng build --prod

test: off

artifacts:
  - path: backend\publish
    name: Backend
  - path: frontend\dist
    name: Frontend

deploy:
  - provider: Environment
    name: Backend
  - provider: Environment
    name: Frontend